title: Pape Index
description: A personal index of research papers
theme: just-the-docs
color_scheme: "light"

url: https://Hongxiang2023.github.io/ReadPaper

# Enable navigation structure
nav_order: 1
search_enabled: true
# Sidebar categories
nav:
  - title: "Category"
    url: /
  - title: "Deep Learning in Epigenomics"
    url: /DL_Epi/
  - title: "DNAm Computational Methods"
    url: /DNAm_mehods/